name: Integration tests

on: ['push']

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: hardhat compile
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: hardhat test --network hardhat
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: hardhat deploy --network mumbai --write true 
      env: 
        FORK_URL: ${{ secrets.FORK_URL }}
        DEV_MNEMONIC: ${{ secrets.DEV_MNEMONIC }}
        DEPLOY_CHAIN: mumbai