# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration tests

on: ['push']

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: hardhat compile
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: hardhat test

    # - uses: actions/checkout@v3 
    # - name: Use Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16.x'
    # # solves issue https://github.com/actions/setup-node/issues/214
    # - name: Reconfigure git to use HTTP authentication
    #   run: >
    #     git config --global url."https://".insteadOf git://
    #     git config --global url."https://github.com/".insteadOf git@github.com:

    # - name: Install dependencies
    #   run: npm install
    # - name: run tests
    #   run: npx hardhat test

      env: 
        FORK_URL: ${{ secrets.FORK_URL }}
        DEV_MNEMONIC: ${{ secrets.DEV_MNEMONIC }}
