name: Integration tests

on:
  push:
    branches: ['main']

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v3.0.0
      name: install
      with:
        cmd: install
    - uses: borales/actions-yarn@v3.0.0
      name: compile
      with:
        cmd: hardhat compile
    - uses: borales/actions-yarn@v3.0.0
      name: tests
      with:
        cmd: hardhat test --network hardhat
      env: 
        FORK_URL: ${{ secrets.FORK_URL }}
        DEV_MNEMONIC: ${{ secrets.DEV_MNEMONIC }}

    - uses: borales/actions-yarn@v3.0.0
      name: deploy
      with:
        cmd: hardhat deploy --network mumbai --write true 
      env:
        DEV_MNEMONIC: ${{ secrets.DEV_MNEMONIC }}
        MUMBAI_URL: ${{secrets.MUMBAI_URL}}
        DEPLOY_CHAIN: mumbai
