name: Integration tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  monolith:
    runs-on: ubuntu-latest
    env:
      DEV_MNEMONIC: ${{ secrets.DEV_MNEMONIC }}
      MUMBAI_URL: ${{secrets.MUMBAI_URL}}
      FORK_URL: ${{ secrets.FORK_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn install --dev
      - run: yarn compile
      - run: yarn lint-sol
      - run: yarn lint-ts
      - run: yarn test-ts
      - run: rm deployments/mumbai/AludelFactory.json && yarn hardhat deploy --network mumbai --tags templates
